Notebook/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('notes.urls')),

]

notes/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout
from . import views
app_name = "notes"

urlpatterns = [
    url(r'^$', login_required(views.NotesList.as_view()), name='index'),
    url(r'^login/$', login, {'template_name': 'notes/login.html'}, name='login'),
    url(r'^logout/$', login_required(logout), name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', login_required(views.profile), name='profile'),
    url(r'^create_note/$',login_required(views.CreateNote.as_view()), name="create_note"),
    url('^update_note/(?P<pk>[0-9]+)$', login_required(views.UpdateNote), name='update_note'),
    url(r'^delete_note/(?P<pk>[0-9]+)$', views.deleteNote, name='delete_note'),

]

notes/models.py
from django.db.models import *
from django.contrib.auth.models import User
from django.urls import reverse

class Note(Model):
    user = ForeignKey(User, unique=False)
    title = CharField(max_length=200)
    content = CharField(max_length=2000,blank=True )
    dateAndTime = DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('note-detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return ("By: " + self.user.username + " | " + self.title + ": " + self.content + " Date: " +str(self.dateAndTime.date()) + " | Time: " + str(self.dateAndTime.time()))

notes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateNoteForm(forms.Form):
    title = forms.CharField(max_length=200)
    content = forms.CharField(max_length=2000)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required.')
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    username = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class NotesSearchForm(forms.Form):
    search_text = forms.CharField(
        required=False,
        label='Search',
        # widget=forms.TextInput(attrs={'placeholder': 'search here!'})
    )

notes/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, request
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import FormView
from django.contrib.auth.models import User
from django.views.generic import UpdateView
from django.contrib.auth import login, authenticate, update_session_auth_hash
from search_views.filters import BaseFilter
from search_views.views import SearchListView
from django.contrib import messages

from notes.models import Note
from .forms import CreateNoteForm,SignUpForm, NotesSearchForm


def index(request):
    return render(request, 'notes/index.html', {"notes": Note.objects.all()})


def profile(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('notes:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'notes/profile.html', {
        'form': form
    })


class CreateNote(FormView):
    template_name = 'notes/create_note.html'
    success_url = '/'
    form_class = CreateNoteForm

    def form_valid(self, form):
        title = form.cleaned_data['title']
        content = form.cleaned_data['content']
        note = Note()
        note.title = title
        note.content = content
        note.user = self.request.user
        note.save()

        return super(CreateNote, self).form_valid(form)

def UpdateNote(request, pk):
    myNote = get_object_or_404(Note, pk = pk)
    form = CreateNoteForm(initial = {"title":myNote.title, "content": myNote.content})
    if request.method == 'POST':
        form = CreateNoteForm(request.POST)
        if form.is_valid():
            myNote.title = form.cleaned_data['title']
            myNote.content = form.cleaned_data['content']
            myNote.save()
        return redirect("/")
    return render(request, 'notes/update_note.html', {'form':form, "note":myNote})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'notes/signup.html', {'form': form})


class NotesListFilter(BaseFilter):
    search_fields = {
        'search_text': ['title', 'content'],
    }

class NotesList(SearchListView):
    model = Note
    paginate_by = 5  # Generate pages of 30 elements in the table
    template_name = "notes/index.html"
    form_class = NotesSearchForm
    filter_class = NotesListFilter

def deleteNote(request, pk):
    noteDelete = get_object_or_404(Note, pk=pk).delete()
    return redirect('notes:index')

notes/templates/notes/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static "notes/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Bootstrap CSS -->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "notes:index" %}">Notebook</a>
        </div>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li><a href="{% url "notes:create_note" %}">New note</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url "notes:profile" %}">Profile</a></li>
                    <li><a href="{% url "notes:logout" %}">Logout</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block body %}

    {% endblock %}
</div>
<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static "notes/js/bootstrap.min.js" %}"></script>

</body>
</html>

notes/templates/notes/create_note.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">
            <form class="" action="/create_note/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title">
                </div>
                <div class="form-group">
                    <label for="id_content">Content</label>
                    <textarea class="form-control" id="id_content" type="text" name="content" rows="12"></textarea>
                </div>
                <div style="text-align: right">
                <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>

    </div>
{% endblock %}

notes/templates/notes/index.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <form class="form-group" action="" method="GET">
                {% csrf_token %}
                <div class="col-md-11">
                    <input id="id_search_text" class="form-control" name="search_text" placeholder="Search"
                           type="text">
                </div>
                <div class="col-md-1">
                    <button style="display: block; width: 100%;" class="btn btn-primary" type="submit"><span
                            class="glyphicon glyphicon-search"
                            aria-hidden="true"></span></button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <div class="col-md-12">
        {% for note in object_list %}
            <div class="panel panel-default">
                <div class="panel-heading" style="font-size: 16px"><h3 class="panel-title"><a
                        href="{% url "notes:update_note" pk=note.pk %}">{{ note.title }}</a></h3>
                </div>
                <div class="panel-body">
                    {{ note.content }}
                </div>
            </div>
        {% endfor %}
    </div>


    {% if is_paginated %}
        <div class="text-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">{% if not page_obj.has_previous %}
                        <span aria-hidden="true">{% endif %}&laquo;</span><span
                            class="sr-only"></span></a></li>
                {% endif %}
                {% for page in paginator.page_range %}
                    <li {% if page_obj.number == forloop.counter %}class="active"{% endif %}><a
                            href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">{% if not page_obj.has_next %}
                        <span aria-hidden="true">{% endif %}&raquo;</span><span class="sr-only"></span></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock %}


{% comment %}    <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        {% for uNote in notes %}
            <div class="panel panel-default">
                <div class="panel-heading" style="font-size: 16px"><h3 class="panel-title"><a href="{% url "notes:update_note" pk=uNote.pk %}">{{ uNote.title }}</a></h3>
                </div>
                <div class="panel-body">
                    {{ uNote.content }}
                </div>
            </div>

        {% endfor %}
    </div>
    <div class="col-md-2">
    </div>

    <div>{% endcomment %}

{% comment %}
<div class="col-md-12">
    <table class="table">
        <col style="width:10%">
        <col style="width:75%">
        <col style="width:10%">
        <col style="width:5%">

        <thead>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Date</th>
            <th>Created</th>
        </tr>
        </thead>
        <tbody>
        {% for uNote in notes %}
            <tr>
                <td><a href="{% url "notes:update_note" pk=uNote.pk %}">{{ uNote.title }}</a></td>
                <td>{{ uNote.content }}</td>
                <td>{{ uNote.dateAndTime.date }}</td>
                <td>{{ uNote.user }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>{% endcomment %} 

notes/templates/notes/login.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form class="form-signin" name="LoginForm" action="/login/" method="post">
                {% csrf_token %}
                <input type="text" id="username" class="form-control" name="username" placeholder="Username"
                       required=""
                       autofocus=""/>
                <br>
                <input type="password" id="password" class="form-control" name="password" placeholder="Password"
                       required=""/>
                <br>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
            </form>
            <br>
            <div style="text-align: center">
                <a href="{% url "notes:signup" %}">I want an account.</a>
            </div>
        </div>
        <div class="col-md-4"></div>

    </div>
{% endblock %}

notes/templates/notes/profile.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row">
        <div class="col-md-8">
            <h2>Profile details</h2>
            <br>
            <ul class="list-group">
                <li class="list-group-item"><b>Username: </b> {{ user.username }} </li>
                <li class="list-group-item"><b>Email: </b> {{ user.email }} </li>
                <li class="list-group-item"><b>First name: </b> {{ user.first_name }} </li>
                <li class="list-group-item"><b>Last name: </b> {{ user.last_name }} </li>
            </ul>
        </div>
        <div class="col-md-4">
            <h2>Reset password</h2>
            <br>
            <form method="post">
                {% csrf_token %}

                <form class="" action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="password" class="form-control" id="id_old_password" name="old_password" placeholder="Old password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="new_password1" type="password" name="new_password1" placeholder="New password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="new_password2" type="password" name="new_password2" placeholder="Repeat new password">
                    </div>
                    <div class="form-group">
                        <div style="text-align: right">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </form>

            </form>
        </div>
    </div>
{% endblock %}

notes/templates/notes/signup.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

notes/templates/notes/update_note.html
{% extends 'notes/base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">
            <form class="" action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title" value="{{ note.title }}">
                </div>
                <div class="form-group">
                    <label for="id_content">Content</label>
                    <textarea class="form-control" id="id_content" type="text" name="content"
                              rows="12">{{ note.content }}</textarea>
                </div>
                <div class="row">
                    <div class="col-md-6">
                           <button class="btn btn-danger"><a style="text-decoration: none; color: white" href="{% url "notes:delete_note" pk=note.pk %}">Remove</a>
                    </div>
                    <div class="col-md-6">
                        <div style="text-align: right">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>

    </div>
{% endblock %}